### ISSUE TITLE
Grails 5 and Java 8 ?

### ISSUE THREAD

**Issue by aadrian** [matrei/grails-inertia-plugin#1]
Hi,

Is the plug-in still compatible with Grails 5 and Java 8? 

Thank you.

**Comment by matrei** [comment]
Hi @aadrian, branch 1.2.x is compatible with Grails 5/Java 8.
Master branch is now targeting Grails 6/Java 11.

**Comment by aadrian** [comment]
> branch 1.2.x is compatible with Grails 5/Java 8.

@matrei Thank you very much.  That looks great.  Grails 6 seems to have to much stuff "retired"  so many projects can't simply just update to it.
